#ifndef TERMINAL_OUT_OPTIONS_H
#define TERMINAL_OUT_OPTIONS_H

enum class FONT_OPTIONS : char {
  FONT_DEFAULT = 0x00,
  FONT_BOLD_ON = 0x01,
  FONT_BOLD_OFF = 0x02,
  FONT_BRIGHT_ON = 0x04,
  FONT_BRIGHT_OFF = 0x08,
  FONT_UNDERSCORE_ON = 0x10,
  FONT_UNDERSCORE_OFF = 0x20,
  FONT_BLINK_ON = 0x40,
  FONT_BLINK_OFF = 0x7F,
  FG_BLACK = 30,
  FG_RED = 31,
  FG_GREEN = 32,
  FG_BROWN = 33,
  FG_BLUE = 34,
  FG_MAGENTA = 35,
  FG_CYAN = 36,
  FG_WHITE = 37,
  BG_BLACK = 40,
  BG_RED = 41,
  BG_GREEN = 42,
  BG_BROWN = 43,
  BG_BLUE = 44,
  BG_MAGENTA = 45,
  BG_CYAN = 46,
  BG_WHITE = 47
};

#endif
